name: Build & Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rag-server:$IMAGE_TAG -t ${{ secrets.DOCKER_USERNAME }}/rag-server:latest .

      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/rag-server:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/rag-server:latest
